### ISSUE TITLE
Working demo of INT

### ISSUE THREAD

**Issue by vksysd** [p4lang/p4-applications#20]
Can someone please point me to a working demo on INT. I have tried p4factory repository demo but it fails on building the switch docker image. Kindly provide a working demo link.

**Comment by mhira1** [comment]
As you are aware, we are working on version 1.0 of the INT specification in the P4 applications working group. We also plan to work on a reference implementation in the working group based on v1.0 of the specifications once this version is finalized. 

Since this is more of a question, not an issue against the current drafts of the specifications, I am closing this issue. Please follow working group activities over the mailing list for announcements related to release of version 1.0 and reference implementations.

**Comment by agrml** [comment]
@coolvikas Did you find a working commit or VM image?
